FROM bitnami/spark:3.5.2

USER root

# Install additional dependencies
RUN install_packages curl

# Download necessary jars and add them to Spark's jars directory

RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar \
    && curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar \
    && curl https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.6.1/iceberg-spark-runtime-3.5_2.12-1.6.1.jar --output /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.6.1.jar \
    && curl https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-extensions-3.5_2.12/1.6.1/iceberg-spark-extensions-3.5_2.12-1.6.1.jar --output /opt/bitnami/spark/jars/iceberg-spark-extensions-3.5_2.12-1.6.1.jar \
    && curl https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/1.6.1/iceberg-aws-bundle-1.6.1.jar --output /opt/bitnami/spark/jars/iceberg-aws-bundle-1.6.1.jar

RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

USER 1001
